import { GoogleGenerativeAI } from "@google/generative-ai";
import { getContextForEpisode } from "../data/knowledge";

interface RecallResponse {
    character_name: string;
    actor_name: string;
    safe_summary: string;
}

export const analyzeScene = async (apiKey: string, imageBase64: string, season: number, episode: number): Promise<RecallResponse> => {
    if (!apiKey) {
        throw new Error("API Key is missing");
    }

    // Remove data:image/png;base64, prefix if present for Gemini SDK
    const base64Data = imageBase64.split(',')[1] || imageBase64;

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({
        model: "gemini-1.5-flash",
        generationConfig: {
            responseMimeType: "application/json",
        }
    });

    // Retrieve RAG Context
    const ragContext = getContextForEpisode(season, episode);

    const prompt = `
    You are an expert on the TV show 'Succession'. I am sending you a screen capture of the show.
    
    TASK:
    1. VISUAL SCAN: Strictly analyze the image to identify which character(s) are present. Do not guess. If you see a face you recognize from the cast, identify them.
    2. CONTEXT AWARENESS: The user is watching Season ${season}, Episode ${episode}.
       - Context Summary of where the user is in the plot: "${ragContext}"
    3. DYNAMIC SUMMARY: Generate a 2-sentence "Recall" summary for the identified character(s).
       - This summary MUST describe their status, motivation, and relationships *at this specific point* in the timeline (S${season}E${episode}).
       - It must be generated by YOU based on your knowledge of the show, not looked up from a list.

    CRITICAL SPOILER RULES:
    - You must NEVER reveal events that happen after Season ${season}, Episode ${episode}.
    - If the user is on Season 1, do NOT mention the Season 3 shareholder vote.
    - If the user is on Season 2, do NOT mention Logan's death (Season 4).
    - Treat this as a "Streaming Companion" that respects linear time.

    Output Format: JSON { "character_name": "...", "actor_name": "...", "safe_summary": "..." }
    If multiple characters are present, choose the most prominent one.
    If the image is NOT from Succession (e.g. a random person, a blank screen), identify what is visibly there (e.g. "Unknown Person", "Black Screen") and state that it is not a know main character.
  `;

    try {
        const result = await model.generateContent([
            prompt,
            {
                inlineData: {
                    data: base64Data,
                    mimeType: "image/png",
                },
            },
        ]);

        const responseText = result.response.text();
        return JSON.parse(responseText) as RecallResponse;
    } catch (error) {
        console.error("Gemini Analysis Error:", error);
        throw error;
    }
};
